# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'HackGT-HealthKit' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HackGT-HealthKit
pod 'SSBouncyButton', '~> 1.0'
pod 'SwiftyButton'

end

target 'HackGT-HealthKit WatchKit App' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HackGT-HealthKit WatchKit App

end

target 'HackGT-HealthKit WatchKit Extension' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HackGT-HealthKit WatchKit Extension

end
